Repository gomozigota-metacoop/kaif-station, pull requests merged in 2025-01, with the labels that each got.

#3 remove bingus
  Resources/Prototypes/Entities/bingus_species.yml
Labels: Changes: No C#

#10 [Feature] Mr Proper
  Resources/Audio/_Kaif/Ambience/Mobs/mr_proper.ogg
  Resources/Prototypes/_Kaif/Entities/Mobs/NPCs/mrproper.yml
  Resources/Textures/_Kaif/mrproper.rsi/alive.png
  Resources/Textures/_Kaif/mrproper.rsi/meta.json
Labels: Changes: Sprites, Changes: Audio, Changes: No C#

#12 [Port] Respawn
  Content.Client/Ghost/GhostSystem.cs
  Content.Client/UserInterface/Systems/Ghost/GhostUIController.cs
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml
  Content.Client/UserInterface/Systems/Ghost/Widgets/GhostGui.xaml.cs
  Content.Server/GameTicking/GameTicker.GamePreset.cs
  Content.Server/GameTicking/GameTicker.Spawning.cs
  Content.Server/Ghost/GhostReturnToRoundSystem.cs
  Content.Shared/CCVar/CCVars.GhostRespawn.cs
  Content.Shared/Ghost/SharedGhostSystem.cs
  Resources/Locale/en-US/ghost/ghost-gui.ftl
  Resources/Locale/en-US/ghost/ghost-respawn.ftl
  Resources/Locale/ru-RU/ghost/ghost-gui.ftl
  Resources/Locale/ru-RU/ghost/ghost-respawn.ftl
Labels: Changes: UI

#13 Update some shit
  Resources/Locale/ru-RU/discord/round-notifications.ftl
Labels: Changes: No C#

#18 [Feature] Stinky Poooo!
  Resources/Audio/_Kaif/Emotions/fart/fart_1.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_2.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_3.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_4.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_5.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_6.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_7.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_8.ogg
  Resources/Audio/_Kaif/Emotions/fart/fart_9.ogg
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
  Resources/Prototypes/_Goobstation/SoundCollections/emotes.yml
  Resources/Prototypes/_Kaif/Entities/Markers/Spawners/mobs.yml
  Resources/Prototypes/_Kaif/Entities/Mobs/NPCs/poopsy.yml
  Resources/Prototypes/_Kaif/SoundCollections/emotions.yml
  Resources/Textures/_Kaif/poopsy.rsi/alive.png
  Resources/Textures/_Kaif/poopsy.rsi/dead.png
  Resources/Textures/_Kaif/poopsy.rsi/meta.json
Labels: Changes: Sprites, Changes: Audio, Changes: No C#
